/**
 * What each kind of business hears in its first WhatsApp.
 *
 * Two sentences, in the shape of the Trades opener Keylo signed off: what
 * THAT business's customers want to see before they choose, then "That's
 * exactly what we build:" and the three things its site would carry. And a
 * closing line to suit. lib/pitch-match.js picks the one for a lead.
 *
 * Rules every pitch keeps (test/pitches.test.js holds them to it): two
 * sentences, no "simple", no "one page", no dashes, UK English, plain and
 * warm. Edit freely; the test will say if a line breaks one.
 */

/** Kinds of business, each owning the search terms (lib/sic.js) it covers. */
export const PITCHES = [
  /* Building trades */
  {
    business: "roofer",
    terms: ['roofer', 'roofers', 'roofing', 'roof repairs', 'flat roofing'],
    pitch: "For a roofer, people want to see roofs you've done and know you'll come out quickly when a leak won't wait. That's exactly what we build: a clean site with photos of your roofs, the repairs and flat roofing you take on, and a call button, so homeowners can reach you fast when something goes wrong.",
    close: "Cheers, and hope the weather stays kind to you.",
  },
  {
    business: "electrician",
    terms: ['electrician', 'electricians', 'electrical', 'sparks'],
    pitch: "For an electrician, people want to know you're qualified and registered before they let you near their wiring. That's exactly what we build: a tidy site with your registration details, the work you do from rewires to landlord safety certificates, and a call button, so people know they're in safe hands.",
    close: "Thanks a lot, and hope the week goes well.",
  },
  {
    business: "plumber",
    terms: ['plumber', 'plumbers', 'plumbing'],
    pitch: "For a plumber, people usually need someone fast, so they want a number they can ring straight away and a rough idea of what you charge. That's exactly what we build: a clear site with your prices, the areas you cover, and a big call button, so when a pipe bursts nearby, it's your phone that rings.",
    close: "Cheers, and hope the phone keeps ringing.",
  },
  {
    business: "heating engineer",
    terms: ['heating engineer', 'boiler', 'gas engineer', 'gas safe'],
    pitch: "For a heating engineer, customers want to see you're Gas Safe registered and know you can sort their boiler before the house goes cold. That's exactly what we build: a smart site with your Gas Safe number, your servicing and installation work, and a call button, so people can book you with confidence.",
    close: "Thanks so much, and hope the diary stays full.",
  },
  {
    business: "plasterer",
    terms: ['plasterer', 'plasterers', 'plastering'],
    pitch: "For a plasterer, people want to see smooth, even finishes and know you'll leave the place tidy afterwards. That's exactly what we build: a neat site with photos of walls and ceilings you've done, the areas you cover, and a quick way to ask for a quote, so new work comes straight to you.",
    close: "Cheers, and all the best with the business.",
  },
  {
    business: "rendering specialist",
    terms: ['rendering', 'render'],
    pitch: "For a rendering specialist, homeowners want to see how a finished house front looks and which colours and finishes they can choose from. That's exactly what we build: a fresh site with before and after photos, the render types you offer, and a quote button, so people can picture their home before they call.",
    close: "Thanks a lot, and here's to plenty of dry days.",
  },
  {
    business: "joiner",
    terms: ['joiner', 'joiners', 'joinery'],
    pitch: "For a joiner, customers want to see the quality of what you make, from staircases to bespoke doors and windows. That's exactly what we build: a handsome site with a gallery of your joinery, the pieces you make to order, and an easy enquiry form, so people can bring their ideas straight to you.",
    close: "Cheers, and all the best in the workshop.",
  },
  {
    business: "carpenter",
    terms: ['carpenter', 'carpenters', 'carpentry'],
    pitch: "For a carpenter, people want to see the fitted work you've done and feel sure you'll do a careful, tidy job in their home. That's exactly what we build: a warm site with photos of your fitted wardrobes, shelving and doors, the areas you cover, and a call button, so new customers can get in touch easily.",
    close: "Thanks so much, and have a great week.",
  },
  {
    business: "tiler",
    terms: ['tiler', 'tilers', 'tiling'],
    pitch: "For a tiler, customers want to see straight lines and clean grout in real kitchens and bathrooms before they trust you with theirs. That's exactly what we build: a crisp site with detailed photos of your work, the rooms and tiles you handle, and a quote button, so people can see your standard before they even call.",
    close: "Cheers, and hope the next job goes smoothly.",
  },
  {
    business: "floor fitter",
    terms: ['flooring', 'floor fitter', 'wood flooring'],
    pitch: "For a floor fitter, people want to see finished floors in real homes and know which types of flooring you can lay. That's exactly what we build: a clean site with photos of your wood, laminate and vinyl floors, the areas you cover, and a call button, so customers can pick the right fitter first time.",
    close: "Thanks a lot, and have a good one.",
  },
  {
    business: "carpet fitter",
    terms: ['carpet fitter'],
    pitch: "For a carpet fitter, customers want to know the carpet will go down neatly with tidy edges and that the price is fair. That's exactly what we build: a friendly site with photos of rooms you've carpeted, the areas you cover, and an easy way to book a measuring visit, so the calls come straight to you.",
    close: "Cheers, and wishing you a steady run of work.",
  },
  {
    business: "painter and decorator",
    terms: ['painter', 'painters', 'decorator', 'decorators', 'painting and decorating', 'painter decorator'],
    pitch: "For a painter and decorator, people want to see rooms you've transformed and feel sure you'll be tidy and respectful in their home. That's exactly what we build: a bright site with before and after photos, the interior and exterior work you do, and a call button, so new customers can reach you in a tap.",
    close: "Thanks so much, and have a lovely week.",
  },
  {
    business: "glazier",
    terms: ['glazier', 'glaziers', 'glazing'],
    pitch: "For a glazier, customers often need a broken pane sorted quickly, so they want a number to ring and to know you'll come out. That's exactly what we build: a practical site with your emergency repairs and boarding up, the areas you cover, and a call button, so urgent jobs come straight to you.",
    close: "Cheers, and all the best with everything.",
  },
  {
    business: "window fitter",
    terms: ['double glazing', 'window fitter', 'windows and doors'],
    pitch: "For a window fitter, homeowners want to see the styles and colours on offer and know the work is properly certified and guaranteed. That's exactly what we build: a polished site with photos of your installs, the windows and doors you supply, and a quote request form, so people can start planning their new windows with you.",
    close: "Thanks a lot, and hope business is going well.",
  },
  {
    business: "kitchen fitter",
    terms: ['kitchen fitter', 'kitchen installation'],
    pitch: "For a kitchen fitter, people want to see kitchens you've fitted and feel confident you'll keep the mess and the timings under control. That's exactly what we build: a stylish site with a gallery of your kitchens, how a typical fit works, and a quote button, so homeowners can picture their new kitchen with you.",
    close: "Cheers, and all the best with the next fit.",
  },
  {
    business: "bathroom fitter",
    terms: ['bathroom fitter', 'bathroom installation'],
    pitch: "For a bathroom fitter, customers want to see finished bathrooms and know you'll handle everything from plumbing to tiling without them juggling trades. That's exactly what we build: a fresh site with photos of your bathrooms, the full service you offer, and a call button, so people can hand the whole job to you.",
    close: "Thanks so much, and enjoy the rest of your day.",
  },
  {
    business: "shopfitter",
    terms: ['shopfitter', 'shopfitting'],
    pitch: "For a shopfitter, business owners want to see finished shops and know you'll deliver on time so they can open their doors. That's exactly what we build: a professional site with a portfolio of your shop interiors, the sectors you work in, and a contact form, so new clients can brief you straight away.",
    close: "Cheers, and good luck with the next project.",
  },
  {
    business: "finishing contractor",
    terms: ['finishing'],
    pitch: "For a finishing contractor, builders and homeowners want to see the quality of your final touches and know the job will be handed over ready to use. That's exactly what we build: a sharp site with photos of your finished interiors, the trades you cover, and a quote button, so new work finds you easily.",
    close: "Thanks a lot, and all the best on site.",
  },
  {
    business: "demolition contractor",
    terms: ['demolition'],
    pitch: "For a demolition contractor, clients want to know you're properly insured, work safely and will leave the site clear afterwards. That's exactly what we build: a solid site with photos of past projects, your accreditations and insurance, and a direct call button, so developers and homeowners can bring you in without a second thought.",
    close: "Cheers, and here's to plenty of good jobs ahead.",
  },

  /* Groundworks, specialist building, energy, gardens and outdoors */
  {
    business: "groundworker",
    terms: ['groundworks', 'groundworker', 'groundworkers', 'excavation', 'site preparation'],
    pitch: "For a groundworker, builders and homeowners want proof you can handle the digging, drainage and foundations properly before they book you in. That's exactly what we build: a solid site with photos of your finished groundworks, the machinery and services you offer, and a quick way to ask for a quote, so the next job lands with you.",
    close: "Cheers, and all the best on site.",
  },
  {
    business: "muckaway service",
    terms: ['muckaway'],
    pitch: "For a muckaway service, builders want to know you'll turn up when you say and take the spoil away legally. That's exactly what we build: a tidy site with photos of your grab and tipper lorries, your waste carrier licence, and a button to book a collection, so contractors can get sites cleared without chasing anyone.",
    close: "Thanks, and hope the lorries keep rolling.",
  },
  {
    business: "scaffolder",
    terms: ['scaffolder', 'scaffolders', 'scaffolding'],
    pitch: "For a scaffolder, builders and homeowners want to see you're insured, safe and able to get the scaffold up on the day you promised. That's exactly what we build: a professional site with photos of recent jobs, your insurance and accreditations, and a quick quote form, so builders and roofers know exactly who to ring.",
    close: "Cheers, and stay safe up there.",
  },
  {
    business: "damp proofing specialist",
    terms: ['damp proofing'],
    pitch: "For a damp proofing specialist, homeowners want to understand what's causing the problem and trust that the fix comes with a proper guarantee. That's exactly what we build: a clear site with the treatments you offer, before and after photos, and an easy way to book a survey, so worried homeowners call you first.",
    close: "Thanks very much, and all the best with it.",
  },
  {
    business: "underpinning specialist",
    terms: ['underpinning'],
    pitch: "For an underpinning specialist, homeowners dealing with subsidence want reassurance that you've done this many times and can work alongside their insurer and engineer. That's exactly what we build: a trustworthy site with past projects explained, the methods you use, and a direct line to book a survey, so anxious homeowners feel confident picking you.",
    close: "Thanks for your time, and best wishes.",
  },
  {
    business: "steel erector",
    terms: ['steel erection'],
    pitch: "For a steel erector, main contractors want to see the frames you've put up, your safety record, and proof you can keep to a programme. That's exactly what we build: a professional site with a gallery of completed structures, your accreditations and capacity, and a tender enquiry form, so bigger contracts start coming your way.",
    close: "Cheers, and good luck with the next frame.",
  },
  {
    business: "specialist construction firm",
    terms: ['specialised construction'],
    pitch: "For a specialist construction firm, clients want to see exactly what you're expert in and proof you've delivered it on similar projects. That's exactly what we build: a sharp site with your specialist services, detailed case studies, and a straightforward enquiry form, so the right clients find you instead of a general builder.",
    close: "Thanks so much, and all the best with the business.",
  },
  {
    business: "insulation installer",
    terms: ['insulation', 'loft insulation', 'cavity wall'],
    pitch: "For an insulation installer, homeowners want to know how much warmer their home will feel and whether they qualify for any grants. That's exactly what we build: a friendly site with the loft and cavity wall work you do, clear grant information, and an easy survey booking form, so households looking to cut their bills come to you.",
    close: "Thanks so much, and keep those homes cosy.",
  },
  {
    business: "builder",
    terms: ['builder', 'builders', 'building contractor', 'construction'],
    pitch: "For a builder, homeowners want to see finished projects, read what past clients say, and feel sure you'll turn up and finish on time. That's exactly what we build: a professional site with a gallery of completed work, reviews from local customers, and a quote request form, so good enquiries reach you directly.",
    close: "Cheers, and all the best with the builds.",
  },
  {
    business: "extension builder",
    terms: ['extension builder'],
    pitch: "For an extension builder, homeowners want to picture their own project, so they look for finished extensions and how you handle planning and building regs. That's exactly what we build: a polished site with photos of completed extensions, a clear outline of your process, and a way to book a home visit, so serious enquiries land with you.",
    close: "Thanks for reading, and have a great week.",
  },
  {
    business: "loft conversion specialist",
    terms: ['loft conversion'],
    pitch: "For a loft conversion specialist, homeowners want to see what their loft could become and understand dormers, roof windows and planning before they commit. That's exactly what we build: a bright site with photos of finished lofts, the conversion types you offer, and a button to book a survey, so families needing more room come to you first.",
    close: "Many thanks, and best of luck with the lofts.",
  },
  {
    business: "ducting installer",
    terms: ['ducting'],
    pitch: "For a ducting installer, contractors and business owners want to see the ventilation and extraction systems you've fitted and know you can work around a busy site. That's exactly what we build: a professional site with photos of installed ductwork, the sectors you cover, and a straightforward enquiry form, so commercial jobs find their way to you.",
    close: "Cheers, and thanks for taking a look.",
  },
  {
    business: "lift installer",
    terms: ['lift installation'],
    pitch: "For a lift installer, building owners want to see the lifts you've fitted and be sure you'll handle servicing and inspections long after handover. That's exactly what we build: a polished site with your past installations, your maintenance packages, and a direct enquiry form, so property managers and developers can reach you easily.",
    close: "Thanks very much, and all the best going forward.",
  },
  {
    business: "aerial fitter",
    terms: ['aerial fitter', 'satellite'],
    pitch: "For an aerial fitter, people just want their TV working again, so they look for someone local who can come out quickly at a fair price. That's exactly what we build: a clean site with the aerial and satellite work you do, your call out prices, and a tap to call button, so lost signals turn into booked jobs.",
    close: "Cheers, and here's to perfect reception.",
  },
  {
    business: "bricklayer",
    terms: ['bricklayer', 'bricklayers', 'bricklaying', 'bricks'],
    pitch: "For a bricklayer, customers want to see how neat your pointing and finishing is before they trust you with their walls or extension. That's exactly what we build: a tidy site with detailed photos of your brickwork, the jobs you take on, and a quick quote button, so builders and homeowners get in touch with you directly.",
    close: "Thanks, and all the best with the brickwork.",
  },
  {
    business: "stonemason",
    terms: ['stonemason', 'stonemasons', 'stone masonry', 'stonework'],
    pitch: "For a stonemason, clients want to see the quality of your craftsmanship, whether that's a dry stone wall, a restored frontage or a carved piece. That's exactly what we build: a handsome site with a gallery of your stonework, the restoration and repair work you take on, and an easy enquiry form, so people who value proper craft find you.",
    close: "Thanks so much, and keep up the lovely work.",
  },
  {
    business: "dryliner",
    terms: ['dryliner', 'drylining', 'stud walls'],
    pitch: "For a dryliner, contractors and homeowners want to know you'll put up straight walls and ceilings quickly and leave a finish ready for decorating. That's exactly what we build: a neat site with photos of your stud walls and ceilings, the areas you cover, and a quick quote form, so steady work comes straight to you.",
    close: "Cheers, and hope the week goes smoothly.",
  },
  {
    business: "solar installer",
    terms: ['solar', 'solar panels', 'solar installer', 'pv panels'],
    pitch: "For a solar installer, homeowners want to know which panels would suit their roof, what they might save, and that you're MCS certified. That's exactly what we build: a bright site with photos of recent installs, the panels and batteries you fit, and a survey request form, so local homeowners come to you rather than a national firm.",
    close: "Thanks a lot, and here's to sunny days.",
  },
  {
    business: "EV charger installer",
    terms: ['ev charger'],
    pitch: "For an EV charger installer, drivers want to know which chargers you fit, roughly what it costs, and that you're approved to do it properly. That's exactly what we build: a sharp site with the chargers you install, clear pricing, and a quick booking form, so new electric car owners pick you when they collect their keys.",
    close: "Cheers, and happy charging.",
  },
  {
    business: "heat pump installer",
    terms: ['heat pump', 'heat pumps', 'air source', 'ground source', 'renewables'],
    pitch: "For a heat pump installer, homeowners want to understand how an air or ground source system would work in their home and whether they qualify for a grant. That's exactly what we build: a clear site with the systems you fit, an explanation of the Boiler Upgrade Scheme, and a survey booking form, so homeowners ready to switch call you.",
    close: "Thanks, and all the best keeping homes warm.",
  },
  {
    business: "landscaper",
    terms: ['landscaper', 'landscapers', 'landscaping'],
    pitch: "For a landscaper, homeowners want to be inspired by gardens you've already transformed and get a feel for your style before inviting you round. That's exactly what we build: a lovely site with a gallery of finished gardens, the services you offer, and a way to book a design visit, so people planning a new garden come to you.",
    close: "Thanks so much, and happy landscaping.",
  },
  {
    business: "gardener",
    terms: ['gardener', 'gardeners'],
    pitch: "For a gardener, people want someone reliable who'll keep their garden tidy week after week, and they like to know what's included and roughly what it costs. That's exactly what we build: a friendly site with the jobs you cover, your regular visit options, and a quick contact button, so local households can book you in without any fuss.",
    close: "Cheers, and have a lovely day in the garden.",
  },
  {
    business: "grounds maintenance company",
    terms: ['grounds maintenance'],
    pitch: "For a grounds maintenance company, property managers and businesses want to see the sites you already look after and know you'll turn up on schedule all year. That's exactly what we build: a professional site with examples of the grounds you maintain, your contract options, and a quick enquiry form, so commercial clients can find and trust you.",
    close: "Many thanks, and all the best with the contracts.",
  },
  {
    business: "tree surgeon",
    terms: ['tree surgeon', 'tree surgery', 'arborist'],
    pitch: "For a tree surgeon, homeowners want to know you're qualified, fully insured and able to take a tree down safely without damaging anything nearby. That's exactly what we build: a solid site with photos of your work, your qualifications and insurance, and a quick quote form, so people with an overgrown or dangerous tree call you first.",
    close: "Cheers, and stay safe up in the canopy.",
  },
  {
    business: "fencer",
    terms: ['fencer', 'fencing', 'fence installer'],
    pitch: "For a fencer, homeowners want to see the styles you put up and know the posts will stand firm through the next winter storm. That's exactly what we build: a tidy site with photos of your fences and gates, the panel types you supply, and a quick quote button, so neighbours who spot your work can find you.",
    close: "Thanks, and all the best with the fencing.",
  },
  {
    business: "driveway and paving company",
    terms: ['paving', 'paver', 'driveway', 'driveways', 'block paving'],
    pitch: "For a driveway and paving company, homeowners want to see plenty of finished driveways before trusting you with the front of their house. That's exactly what we build: a polished site with a gallery of your block paving and patios, the materials and colours you offer, and a quote request form, so anyone planning a new driveway calls you first.",
    close: "Cheers, and good luck with the next driveway.",
  },
  {
    business: "tarmac contractor",
    terms: ['tarmac'],
    pitch: "For a tarmac contractor, customers want to see real driveways and car parks you've laid and know the work comes with a guarantee they can rely on. That's exactly what we build: a trustworthy site with photos of your tarmac driveways and car parks, your written guarantee, and a quote request form, so customers can book you with confidence.",
    close: "Thanks very much, and all the best out there.",
  },
  {
    business: "artificial grass installer",
    terms: ['artificial grass', 'astroturf'],
    pitch: "For an artificial grass installer, homeowners want to see how real it looks up close, how it copes with kids and pets, and what it costs. That's exactly what we build: a fresh site with before and after photos, the grass ranges you fit, and a form to book a home measure, so people tired of mowing come to you.",
    close: "Cheers, and enjoy the rest of the week.",
  },
  {
    business: "lawn care service",
    terms: ['lawn care', 'lawn treatment'],
    pitch: "For a lawn care service, homeowners want to know what you'll do each season and see proof that patchy, mossy lawns really do come back. That's exactly what we build: a bright site with before and after photos, your seasonal treatment plans, and an easy enquiry form, so people fed up with their lawn get in touch.",
    close: "Thanks, and hope the lawns keep you busy.",
  },
  {
    business: "turfing company",
    terms: ['turfing'],
    pitch: "For a turfing company, homeowners want to see how quickly a tired garden becomes a lush new lawn and know the ground will be prepared properly. That's exactly what we build: a clean site with before and after photos, how you prepare and lay the turf, and a quote request button, so anyone wanting a new lawn books you.",
    close: "Cheers, and hope the phone keeps ringing.",
  },
  {
    business: "shed builder",
    terms: ['shed builder', 'sheds'],
    pitch: "For a shed builder, people want to see the sizes and styles you make and know their shed will stay dry and solid for years. That's exactly what we build: a practical site with photos of finished sheds, your sizes and prices, and an easy order enquiry form, so local customers come to you instead of a flatpack store.",
    close: "Thanks, and all the best in the workshop.",
  },
  {
    business: "garden room builder",
    terms: ['garden rooms'],
    pitch: "For a garden room builder, homeowners want to picture one as their office, gym or studio and understand insulation, electrics and planning before spending. That's exactly what we build: a stylish site with photos of finished garden rooms, your specifications and price guide, and a form to book a design consultation, so serious buyers get in touch with you.",
    close: "Many thanks, and have a brilliant week.",
  },
  {
    business: "summerhouse and log cabin supplier",
    terms: ['summerhouse', 'log cabin'],
    pitch: "For a summerhouse and log cabin supplier, customers want to browse your models, check sizes and timber thickness, and see them finished in real gardens. That's exactly what we build: a warm site with a gallery of your cabins, clear sizes and prices, and an easy enquiry form, so people dreaming of a garden retreat choose you.",
    close: "Thanks so much, and have a lovely day.",
  },

  /* Home services, cleaning and repairs */
  {
    business: "domestic cleaner",
    terms: ['cleaner', 'cleaners', 'cleaning', 'domestic cleaner'],
    pitch: "For a domestic cleaner, most people want to know they can trust who's coming into their home and whether you have a regular slot free. That's exactly what we build: a welcoming site with reviews from local clients, the areas and days you cover, and an easy way to enquire, so new households can book you with confidence.",
    close: "Thanks so much, and have a lovely day.",
  },
  {
    business: "commercial cleaning company",
    terms: ['commercial cleaning', 'office cleaning'],
    pitch: "For a commercial cleaning company, most businesses want to see that you're reliable, insured and happy to work around their opening hours. That's exactly what we build: a professional site with the premises you look after, your insurance and vetting details, and a quick quote form, so office managers can shortlist you straight away.",
    close: "Many thanks, and all the best with the contracts.",
  },
  {
    business: "end of tenancy cleaner",
    terms: ['end of tenancy'],
    pitch: "For an end of tenancy cleaner, tenants mostly want to know the clean will help them get their deposit back and exactly what it will cost. That's exactly what we build: an organised site with your cleaning checklist, fixed prices by property size, and a booking form, so tenants and letting agents can book you in a few minutes.",
    close: "Cheers, and good luck with the bookings.",
  },
  {
    business: "window cleaner",
    terms: ['window cleaner', 'window cleaners', 'window cleaning'],
    pitch: "For a window cleaner, most people want to know if you cover their street, how often you come round and roughly what it costs. That's exactly what we build: a tidy site with the rounds you cover, your prices by house size, and a quick way to sign up, so new customers can join your round without chasing you.",
    close: "Thanks, and hope the weather stays kind.",
  },
  {
    business: "chimney sweep",
    terms: ['chimney sweep', 'chimney sweeps'],
    pitch: "For a chimney sweep, most people want to know you're properly qualified and that you'll leave the room as clean as you found it. That's exactly what we build: a smart site with your accreditations, what each sweep includes, and an easy booking form, so households can get booked in well before the colder months.",
    close: "Thanks very much, and keep the fires burning.",
  },
  {
    business: "oven cleaning business",
    terms: ['oven cleaning'],
    pitch: "For an oven cleaning business, customers mostly want to see what their oven will look like afterwards and know the price upfront. That's exactly what we build: a bright site with before and after photos, clear prices from single ovens to range cookers, and a booking form, so people can pick a slot there and then.",
    close: "Thanks so much, and hope to speak soon.",
  },
  {
    business: "carpet cleaner",
    terms: ['carpet cleaning'],
    pitch: "For a carpet cleaner, most people want proof you can shift stubborn stains and to know how soon they can walk on the carpet again. That's exactly what we build: a fresh site with before and after photos, prices per room, and your typical drying times, so homeowners and landlords can book you without the back and forth.",
    close: "Cheers, and hope business is going well.",
  },
  {
    business: "pressure washing business",
    terms: ['pressure washing', 'jet washing'],
    pitch: "For a pressure washing business, people want to see grimy driveways and patios come up like new before they trust you with theirs. That's exactly what we build: a bold site with a gallery of before and after shots, the surfaces you clean, and a quick quote button, so homeowners can see the difference and get in touch.",
    close: "Thanks a lot, and have a great week.",
  },
  {
    business: "gutter cleaning business",
    terms: ['gutter cleaning'],
    pitch: "For a gutter cleaning business, most people want proof the job's been done properly and to know you're insured to work at height. That's exactly what we build: a practical site with camera photos from inside the gutters, your prices by house type, and a call button, so homeowners can get it sorted before the next downpour.",
    close: "Many thanks, and stay dry out there.",
  },
  {
    business: "pest control business",
    terms: ['pest control', 'exterminator', 'rat catcher'],
    pitch: "For a pest control business, people with rats or mice want someone who can come out quickly and deal with it discreetly. That's exactly what we build: a calm site with the pests you deal with, the areas you cover, and a big call button, so worried households and businesses can reach you straight away.",
    close: "Thanks for your time, and best of luck.",
  },
  {
    business: "wasp nest removal service",
    terms: ['wasp nest'],
    pitch: "For a wasp nest removal service, people want to know you can come out the same day and what it will cost. That's exactly what we build: a clear site with your fixed call out price, the areas you cover, and a tap to call button, so anyone with a nest by the back door can ring you right away.",
    close: "Cheers, and hope the busy season treats you well.",
  },
  {
    business: "removals company",
    terms: ['removals', 'removals company'],
    pitch: "For a removals company, people want to feel their belongings are in safe hands and get a quote without endless phone calls. That's exactly what we build: a dependable site with reviews from past moves, the services you offer from packing to storage, and an online quote form, so families planning a move can book you early.",
    close: "Thanks so much, and all the best with the moves.",
  },
  {
    business: "man and van service",
    terms: ['man and van'],
    pitch: "For a man and van service, most people just want a quick price and to know if you're free this week. That's exactly what we build: a straightforward site with your van size, your hourly rates, and a WhatsApp button, so people moving a sofa or a whole flat can book you in a couple of taps.",
    close: "Cheers, and hope the van keeps busy.",
  },
  {
    business: "house clearance business",
    terms: ['house clearance', 'house clearances'],
    pitch: "For a house clearance business, people often come to you at a difficult time and want someone respectful who'll charge fairly and recycle what they can. That's exactly what we build: a considerate site with the clearances you handle, how you reuse and recycle items, and a free quote form, so families can arrange it with one less worry.",
    close: "Thank you, and wishing you well.",
  },
  {
    business: "locksmith",
    terms: ['locksmith', 'locksmiths'],
    pitch: "For a locksmith, people are often locked out and stressed, so they want a number they can ring fast and a price they can trust. That's exactly what we build: a reassuring site with a big call button, your call out prices, and your response times, so the next person stuck on their doorstep rings you first.",
    close: "Thanks, and hope the phone keeps ringing.",
  },
  {
    business: "security installer",
    terms: ['cctv', 'security', 'security installer', 'access control', 'alarm installer', 'security systems'],
    pitch: "For a security installer, customers want to see the systems you've fitted and know they're dealing with someone qualified and local. That's exactly what we build: a polished site with photos of your camera, alarm and door entry installs, your accreditations, and a free survey request form, so homes and businesses can get a quote with confidence.",
    close: "Many thanks, and keep up the good work.",
  },
  {
    business: "appliance repair engineer",
    terms: ['appliance repair', 'washing machine repair', 'white goods repair', 'domestic appliance'],
    pitch: "For an appliance repair engineer, anyone with a broken washing machine or fridge wants to know you fix their brand and how soon you can come. That's exactly what we build: a handy site with the appliances and brands you repair, your call out fee, and a booking button, so households can get their white goods working again.",
    close: "Cheers, and hope the week's going well.",
  },
  {
    business: "mower repair business",
    terms: ['mower repair'],
    pitch: "For a mower repair business, gardeners want to know you work on their make of mower and how quickly they'll get it back. That's exactly what we build: a down to earth site with the brands you service, your servicing prices, and your collection details, so people can get their mower sorted before the grass gets away from them.",
    close: "Thanks very much, and enjoy the rest of your day.",
  },
  {
    business: "TV repair specialist",
    terms: ['tv repair'],
    pitch: "For a TV repair specialist, people want to know if their set is worth fixing and whether you can come to them. That's exactly what we build: an honest site with the makes you repair, your diagnostic fee, and a quick enquiry form, so customers can get a straight answer before they buy new.",
    close: "Thanks, and all the best with the repairs.",
  },
  {
    business: "phone repair shop",
    terms: ['phone repair', 'iphone repair'],
    pitch: "For a phone repair shop, most people with a cracked screen want to know the price for their model and how long they'll be without it. That's exactly what we build: a modern site with prices by model, your usual repair times, and a map to your shop, so people nearby can walk in the same day.",
    close: "Cheers, and hope the shop is busy.",
  },
  {
    business: "computer repair business",
    terms: ['laptop repair', 'computer repair'],
    pitch: "For a computer repair business, people want to know you can fix their laptop without losing their files and what it's likely to cost. That's exactly what we build: a trustworthy site with the repairs you handle, clear prices, and a quick way to book a drop off, so worried customers know they're in safe hands.",
    close: "Many thanks, and have a good one.",
  },
  {
    business: "cobbler",
    terms: ['cobbler', 'shoe repair'],
    pitch: "For a cobbler, people want to know you can save their favourite shoes or boots and roughly how long it will take. That's exactly what we build: a charming site with photos of your resoles and restorations, your repair prices, and where to find you, so locals know who to trust with their best boots.",
    close: "Thank you, and all the best with the shop.",
  },
  {
    business: "key cutting service",
    terms: ['key cutting'],
    pitch: "For a key cutting service, people mostly want to know you can copy their type of key and that you're open when they need you. That's exactly what we build: a neat site with the keys you cut, your opening hours, and a map to find you, so people can pop in knowing you'll have them sorted.",
    close: "Cheers, and have a lovely week.",
  },
  {
    business: "upholsterer",
    terms: ['upholsterer', 'upholstery', 're-upholstery'],
    pitch: "For an upholsterer, people want to see how you've brought tired chairs and sofas back to life and get a feel for the fabrics on offer. That's exactly what we build: an elegant site with before and after photos, your fabric options, and a quote form with photo upload, so customers can picture what you could do with theirs.",
    close: "Thanks so much, and happy stitching.",
  },
  {
    business: "furniture repairer",
    terms: ['furniture repair'],
    pitch: "For a furniture repairer, people want to know you can save a treasured piece, from a wobbly chair to a scratched dining table. That's exactly what we build: a warm site with photos of your repairs, the work you take on, and an easy way to send pictures for a quote, so owners can keep their furniture going for years.",
    close: "Thank you, and all the best in the workshop.",
  },
  {
    business: "handyman",
    terms: ['handyman', 'handymen', 'odd jobs'],
    pitch: "For a handyman, people usually have a list of small jobs and want someone reliable who'll actually turn up and do them properly. That's exactly what we build: a friendly site with the jobs you take on, reviews from local customers, and a call button, so people can hand over their to do list with confidence.",
    close: "Cheers, and hope the diary stays full.",
  },
  {
    business: "property maintenance company",
    terms: ['property maintenance'],
    pitch: "For a property maintenance company, landlords and letting agents want someone dependable who can handle repairs quickly and keep them updated. That's exactly what we build: a businesslike site with the services you cover, the areas you work in, and a straightforward way to report a job, so landlords can trust you with their properties.",
    close: "Many thanks, and wishing you a good week.",
  },
  {
    business: "jobbing builder",
    terms: ['jobbing builder'],
    pitch: "For a jobbing builder, people want to see the kind of work you do, from repointing to small extensions, and know you'll give them an honest price. That's exactly what we build: a solid site with photos of finished jobs, the work you take on, and a quick quote form, so homeowners can get you round to have a look.",
    close: "Cheers, and all the best on site.",
  },
  {
    business: "drainage engineer",
    terms: ['drain service', 'drainage', 'blocked drains', 'drain unblocking'],
    pitch: "For a drainage engineer, someone with a blocked drain wants to know you can get there fast and what it's going to cost. That's exactly what we build: a no nonsense site with a big call button, your call out rates, and the areas you cover, so people with a problem can get straight through to you.",
    close: "Thanks for reading, and take care.",
  },
  {
    business: "CCTV drain survey company",
    terms: ['cctv drain'],
    pitch: "For a CCTV drain survey company, homebuyers and landlords want clear footage, a written report they can understand and a quick turnaround. That's exactly what we build: an informative site with sample survey footage, your survey prices, and a booking form, so buyers can get their drains checked before they exchange contracts.",
    close: "Many thanks, and all the best with the surveys.",
  },

  /* Food and drink */
  {
    business: "restaurant",
    terms: ['restaurant'],
    pitch: "For a restaurant, most diners want to read the menu, see what the food looks like, and book a table before they commit to an evening out. That's exactly what we build: a warm site with your menu, photos of your dishes, and online table booking, so more locals choose you when they fancy a meal out.",
    close: "Thanks for your time, and enjoy a busy service.",
  },
  {
    business: "bistro",
    terms: ['bistro'],
    pitch: "For a bistro, people usually want a feel for the atmosphere, a look at this week's specials, and an easy way to reserve a table. That's exactly what we build: a stylish site with your seasonal menu, photos of the food and the room, and a booking button, so regulars and new faces can grab a table without phoning round.",
    close: "All the best, and here's to full tables.",
  },
  {
    business: "gastropub",
    terms: ['gastropub'],
    pitch: "For a gastropub, people want to see the food menu, what's on tap, and whether they can book for Sunday lunch before they head out. That's exactly what we build: a welcoming site with your menus, your Sunday roast and events, and table booking, so locals and visitors pick you for their next meal out.",
    close: "Cheers, and here's to a packed Sunday lunch.",
  },
  {
    business: "licensed cafe",
    terms: ['licensed cafe'],
    pitch: "For a licensed cafe, customers like to know what you serve from breakfast through to evening, including a glass of wine or a cold beer with lunch. That's exactly what we build: a relaxed site with your food and drinks menu, your opening hours, and photos of the space, so people know they can pop in any time of day.",
    close: "Thanks so much, and have a lovely day.",
  },
  {
    business: "cafe",
    terms: ['cafe'],
    pitch: "For a cafe, people mostly want to know when you're open, what's on the menu, and whether it's a nice spot to sit for a while. That's exactly what we build: a friendly site with your menu, opening hours, and photos of your cafe, so locals know where to head for breakfast or lunch.",
    close: "Thanks so much, and enjoy the rest of your day.",
  },
  {
    business: "coffee shop",
    terms: ['coffee shop'],
    pitch: "For a coffee shop, people want to know what you're brewing, which cakes are on the counter, and whether there's somewhere comfy to sit. That's exactly what we build: a cosy site with your coffee and cake menu, opening hours, and photos of your space, so coffee lovers nearby make you their daily stop.",
    close: "Thanks, and hope the coffee keeps flowing.",
  },
  {
    business: "sandwich shop",
    terms: ['sandwich shop'],
    pitch: "For a sandwich shop, most customers just want to see the menu and prices and know they can order ahead so lunch is ready when they arrive. That's exactly what we build: a tidy site with your full menu and prices, opening hours, and a quick way to place an order, so busy workers nearby choose you for lunch.",
    close: "Cheers, and hope the lunch rush treats you well.",
  },
  {
    business: "tea room",
    terms: ['tea room'],
    pitch: "For a tea room, visitors like to see the cakes, the setting, and whether they can book afternoon tea for a birthday or a special treat. That's exactly what we build: a charming site with your afternoon tea menu, photos of your tea room, and easy booking, so people can plan a lovely visit with you.",
    close: "Thank you, and have a lovely day.",
  },
  {
    business: "takeaway",
    terms: ['takeaway', 'takeaways'],
    pitch: "For a takeaway, hungry customers want to see the menu and prices, check you deliver to them, and order or ring through in a couple of taps. That's exactly what we build: a fast site with your full menu, your delivery areas and opening times, and a call button, so orders come straight to you.",
    close: "Cheers, and hope the orders keep flying in.",
  },
  {
    business: "chip shop",
    terms: ['chip shop', 'fish and chips'],
    pitch: "For a chip shop, people want to know when you're frying tonight, what's on the menu, and whether they can ring ahead to collect. That's exactly what we build: a clear site with your menu and prices, your opening hours, and a tap to call button, so locals know where to get their Friday fish and chips.",
    close: "Cheers, and all the best with the fryers.",
  },
  {
    business: "kebab shop",
    terms: ['kebab'],
    pitch: "For a kebab shop, customers heading home late want to know you're still open, what's on the menu, and how to get an order in fast. That's exactly what we build: a bold site with your menu and prices, your late opening hours, and a call to order button, so hungry locals come straight to you.",
    close: "Cheers, and hope the late shift goes well.",
  },
  {
    business: "Chinese takeaway",
    terms: ['chinese takeaway'],
    pitch: "For a Chinese takeaway, customers want to browse the full menu, find their favourite dishes by number, and order for collection or delivery without fuss. That's exactly what we build: a handy site with your numbered menu, set meals for sharing, and a call to order button, so regulars can order their usual without digging out a paper menu.",
    close: "Thanks a lot, and wishing you a busy week.",
  },
  {
    business: "Indian takeaway",
    terms: ['indian takeaway'],
    pitch: "For an Indian takeaway, customers want to browse the curries, check how hot each dish is, and see if you deliver to their street. That's exactly what we build: a colourful site with your full menu and spice levels, your delivery areas, and a call to order button, so Friday night curry orders come straight to you.",
    close: "Many thanks, and all the best with the kitchen.",
  },
  {
    business: "pizza takeaway",
    terms: ['pizza takeaway'],
    pitch: "For a pizza takeaway, people want to see your toppings and deals, check you deliver to them, and get their order in quickly. That's exactly what we build: a lively site with your pizza menu and deals, your delivery areas, and a call to order button, so local orders come to you instead of the big chains.",
    close: "Cheers, and hope the ovens stay busy.",
  },
  {
    business: "caterer",
    terms: ['catering', 'caterer', 'caterers', 'event catering'],
    pitch: "For a caterer, clients want to see the kind of food you serve, the events you've done, and how to get a quote for their date. That's exactly what we build: a polished site with sample menus, photos from past events, and an enquiry form, so bookings for weddings, parties and office lunches come to you.",
    close: "Thanks so much, and good luck with your next event.",
  },
  {
    business: "food truck",
    terms: ['food truck'],
    pitch: "For a food truck, people want to know where you'll be parked this week, what's on the menu, and whether they can book you for an event. That's exactly what we build: a fun site with your weekly locations, your menu, and a booking enquiry form, so fans can track you down and hire you for their party.",
    close: "Cheers, and here's to long queues wherever you park.",
  },
  {
    business: "mobile caterer",
    terms: ['mobile catering'],
    pitch: "For a mobile caterer, event organisers want to see your setup, what you can serve, and whether you're free for their date. That's exactly what we build: a practical site with photos of your van or trailer, your menu options, and an enquiry form, so festivals, fetes and private parties can book you easily.",
    close: "Thanks, and all the best for the season ahead.",
  },
  {
    business: "private chef",
    terms: ['private chef'],
    pitch: "For a private chef, clients want a taste of your cooking style, some sample menus, and a sense of what an evening with you would be like. That's exactly what we build: a refined site with your sample menus, photos of your dishes, and a booking enquiry form, so dinner parties and special occasions come straight to you.",
    close: "Thank you, and all the best with your bookings.",
  },
  {
    business: "bakery",
    terms: ['bakery', 'baker', 'bakers'],
    pitch: "For a bakery, customers want to see what's fresh on the shelves, when you open, and whether they can order ahead for a special occasion. That's exactly what we build: a tempting site with photos of your bakes, your opening hours, and an order enquiry form, so locals know to come early before it all sells out.",
    close: "Warm wishes, and enjoy the early starts.",
  },
  {
    business: "artisan bakery",
    terms: ['artisan bakery'],
    pitch: "For an artisan bakery, customers want to see your sourdough and pastries, learn a little about how you bake, and know which days to come by. That's exactly what we build: a characterful site with photos of your bakes, your story, and your weekly baking days, so bread lovers find you and come back week after week.",
    close: "Thanks for reading, and happy baking.",
  },
  {
    business: "cake maker",
    terms: ['cake maker'],
    pitch: "For a cake maker, customers want to see the cakes you've made before and know you can create something special for their celebration. That's exactly what we build: a pretty site with a gallery of your cakes, your flavours and prices, and an order enquiry form, so birthday and wedding orders land straight with you.",
    close: "Thanks so much, and best wishes with the orders.",
  },
  {
    business: "butcher",
    terms: ['butcher', 'butchers', 'family butcher'],
    pitch: "For a butcher, customers want to know where your meat comes from, what's on offer this week, and whether they can order ahead for the weekend or Christmas. That's exactly what we build: a hearty site with your local suppliers, weekly specials, and an order enquiry form, so regulars can reserve their Sunday joint or Christmas turkey.",
    close: "Cheers, and all the best with the shop.",
  },
  {
    business: "fishmonger",
    terms: ['fishmonger', 'fishmongers'],
    pitch: "For a fishmonger, customers want to know what's come in fresh today, where it was landed, and whether they can have something put aside. That's exactly what we build: a crisp site with your daily catch, your opening hours, and a call to order button, so people know what to pick up for tonight's dinner.",
    close: "Thanks a lot, and hope the catch is good.",
  },
  {
    business: "deli",
    terms: ['deli', 'delicatessen'],
    pitch: "For a deli, customers love to see the cheeses, meats and treats on your counter and find out about hampers and sharing platters. That's exactly what we build: a tasteful site with photos of your counter, your hampers and platters, and your opening hours, so food lovers nearby know where to find something special.",
    close: "Thanks so much, and have a lovely week.",
  },
  {
    business: "farm shop",
    terms: ['farm shop'],
    pitch: "For a farm shop, visitors want to know what's in season, where your produce is grown, and when they can call in for a browse. That's exactly what we build: a rustic site with your seasonal produce, your farm's story, and opening hours with directions, so families make a proper day out of visiting you.",
    close: "Thanks, and all the best on the farm.",
  },
  {
    business: "greengrocer",
    terms: ['greengrocer'],
    pitch: "For a greengrocer, people want to know what's fresh and in season this week and whether you can deliver a box to their door. That's exactly what we build: a cheerful site with your seasonal produce, your opening hours, and veg box ordering, so locals can shop fresh without heading to the supermarket.",
    close: "Cheers, and have a great week ahead.",
  },

  /* Motor, hair and beauty, therapies and pets */
  {
    business: "garage",
    terms: ['garage', 'mechanic', 'mechanics', 'car repair'],
    pitch: "For a garage, most drivers want to know what you can fix, roughly what it will cost, and that other locals trust you with their car. That's exactly what we build: a clean site with your services and prices, your reviews, and a button to book or call, so new customers choose you over the big chains.",
    close: "Cheers, and all the best with the garage.",
  },
  {
    business: "MOT centre",
    terms: ['mot', 'mot centre', 'mot test', 'mot testing'],
    pitch: "For an MOT centre, people want to see the price upfront, find a slot that suits them, and know you can sort any repairs if it fails. That's exactly what we build: a clear site with your MOT price, your opening hours, and a quick booking button, so drivers can get their test in the diary without ringing around.",
    close: "Many thanks, and hope the bays stay full.",
  },
  {
    business: "bodyshop",
    terms: ['bodyshop', 'body shop'],
    pitch: "For a bodyshop, people want to see dents and scrapes you've put right, know you'll deal with their insurer, and get a rough quote without any fuss. That's exactly what we build: a polished site with before and after photos, the insurers you work with, and a quick photo quote form, so drivers happily bring their car to you.",
    close: "Cheers, and hope business is going well.",
  },
  {
    business: "mobile mechanic",
    terms: ['mobile mechanic'],
    pitch: "For a mobile mechanic, people want to know you'll come to their drive or workplace, which areas you cover, and what you can fix on the spot. That's exactly what we build: a handy site with the repairs you handle, the areas you cover, and a tap to call button, so stranded drivers can get hold of you fast.",
    close: "Cheers, and safe travels between jobs.",
  },
  {
    business: "motorbike mechanic",
    terms: ['motorcycle repair', 'motorbike repair'],
    pitch: "For a motorbike mechanic, riders want to know you understand their make of bike, what a service costs, and when they'll have it back. That's exactly what we build: a sharp site with the makes you work on, your service prices, and an easy booking form, so riders trust you with their pride and joy.",
    close: "Cheers, and happy riding when you get the chance.",
  },
  {
    business: "bike shop",
    terms: ['bike shop'],
    pitch: "For a bike shop, people want to see what you have in stock, what a service costs, and whether you can sort a repair this week. That's exactly what we build: a bright site with the bikes and brands you carry, your repair and servicing prices, and your opening hours, so riders come to you instead of ordering online.",
    close: "Thanks a lot, and have a great week.",
  },
  {
    business: "car valeting business",
    terms: ['car valeting'],
    pitch: "For a car valeting business, people want to see cars you've cleaned inside and out, compare your packages, and book a time that suits them. That's exactly what we build: a gleaming site with before and after photos, your valet packages and prices, and online booking, so customers can choose a package and book in a couple of minutes.",
    close: "Thanks, and hope the bookings keep rolling in.",
  },
  {
    business: "car detailer",
    terms: ['car detailing'],
    pitch: "For a car detailer, owners want to see the finish you get on paintwork and know exactly what each treatment involves before they book. That's exactly what we build: a sleek site with a gallery of your finishes, your detailing packages explained, and an enquiry form, so enthusiasts are happy to trust you with their car.",
    close: "Cheers, and keep those cars shining.",
  },
  {
    business: "mobile valet",
    terms: ['mobile valet'],
    pitch: "For a mobile valet, customers want to know you'll come to their home or workplace, which areas you cover, and what each clean costs. That's exactly what we build: a tidy site with your areas, your packages and prices, and a quick booking button, so busy people can get their car cleaned without going anywhere.",
    close: "Cheers, and hope the diary stays nice and full.",
  },
  {
    business: "driving instructor",
    terms: ['driving instructor', 'driving lessons'],
    pitch: "For a driving instructor, learners and parents want to know what lessons cost, whether you teach manual or automatic, and when you have space. That's exactly what we build: an approachable site with your prices and block bookings, the areas you cover, and a way to join your waiting list, so new learners can book with you directly.",
    close: "Thanks, and good luck to all your learners.",
  },
  {
    business: "driving school",
    terms: ['driving school'],
    pitch: "For a driving school, learners want to meet the instructors, compare lesson packages, and know they can start soon in their area. That's exactly what we build: a modern site with your instructor profiles, your lesson and intensive course prices, and an easy enquiry form, so new pupils can choose you with confidence.",
    close: "Thanks, and best wishes to the whole team.",
  },
  {
    business: "hairdresser",
    terms: ['hairdresser', 'hairdressers', 'salon', 'hair salon', 'hair stylist'],
    pitch: "For a hairdresser, clients want to see your cuts and colours, check your prices, and book a slot without having to ring. That's exactly what we build: a stylish site with a gallery of your work, your price list, and online booking, so new clients can find you and fill your chair.",
    close: "Thanks so much, and have a lovely day.",
  },
  {
    business: "barber",
    terms: ['barber', 'barbers', 'barbershop', 'barber shop'],
    pitch: "For a barber, customers want to see the fades and cuts you do, know what a trim costs, and check whether they can walk in or need to book. That's exactly what we build: a smart site with photos of your cuts, your price list, and your opening hours with a booking link, so new faces walk through your door.",
    close: "Cheers, and hope the chair stays busy.",
  },
  {
    business: "beauty salon",
    terms: ['beautician', 'beauty salon', 'beauty therapist', 'tanning salon'],
    pitch: "For a beauty salon, clients want to browse your treatments, see what each one costs, and feel confident they're in good hands before booking. That's exactly what we build: a chic site with your treatment menu and prices, photos of your treatment room, and online booking, so new clients can book their first appointment with ease.",
    close: "Thank you, and have a lovely week.",
  },
  {
    business: "nail tech",
    terms: ['nail bar', 'nails', 'nail tech', 'nail salon', 'nail technician'],
    pitch: "For a nail tech, clients want to scroll through your latest sets, check prices for gels and extensions, and grab a slot that suits them. That's exactly what we build: a colourful site with a gallery of your nail designs, your price list, and online booking, so new clients can book straight from your photos.",
    close: "Thanks, and hope to hear from you soon.",
  },
  {
    business: "lash tech",
    terms: ['lashes', 'lash tech', 'eyelash'],
    pitch: "For a lash tech, clients want to see your lash sets up close, understand classic versus volume, and know what infills cost. That's exactly what we build: a glamorous site with photos of your sets, a clear price list for full sets and infills, and online booking, so clients can book their next appointment in a few taps.",
    close: "Thank you, and hope your week is going beautifully.",
  },
  {
    business: "brow bar",
    terms: ['brow bar'],
    pitch: "For a brow bar, clients want to see brows you've shaped and tinted, know which treatments you offer, and book in quickly. That's exactly what we build: a pretty site with before and after photos, your treatment menu from lamination to threading, and online booking, so new clients can see your work and book straight in.",
    close: "Thanks for reading, and enjoy the rest of your week.",
  },
  {
    business: "tattoo artist",
    terms: ['tattoo', 'tattoo artist', 'tattooist'],
    pitch: "For a tattoo artist, people want to see your portfolio and style before anything else, then know how to book a consultation and what the deposit involves. That's exactly what we build: a bold site with your portfolio, your booking and deposit process, and your aftercare advice, so the right clients come to you for the work you love.",
    close: "Cheers, and keep up the brilliant work.",
  },
  {
    business: "piercer",
    terms: ['piercer', 'piercing'],
    pitch: "For a piercer, people want to know your studio is clean and safe, see the piercings and jewellery you offer, and check prices before they come in. That's exactly what we build: a fresh site with your piercing menu and prices, photos of your jewellery and studio, and clear aftercare advice, so nervous customers feel confident booking with you.",
    close: "Cheers, and hope the studio's keeping you busy.",
  },
  {
    business: "massage therapist",
    terms: ['massage', 'massage therapist'],
    pitch: "For a massage therapist, clients want to know which massages you offer, what each one helps with, and when you're free. That's exactly what we build: a calm site with your treatments and prices, a little about you and your approach, and online booking, so clients can book a session whenever they need to unwind.",
    close: "Thank you, and take good care of yourself.",
  },
  {
    business: "reflexologist",
    terms: ['reflexology'],
    pitch: "For a reflexologist, people who are new to it want to understand what a session involves, who they'll be seeing, and what it costs before booking. That's exactly what we build: a gentle site with a plain explanation of reflexology, your prices and qualifications, and an easy way to book, so curious clients feel comfortable taking the first step.",
    close: "Thanks for your time, and I hope we speak soon.",
  },
  {
    business: "acupuncturist",
    terms: ['acupuncture'],
    pitch: "For an acupuncturist, people want to know what you treat, that you're properly qualified, and what to expect from their first appointment. That's exactly what we build: a thoughtful site with the conditions you help with, your qualifications and memberships, and a straightforward way to book, so nervous newcomers feel ready to give it a try.",
    close: "With thanks, and best wishes for the week ahead.",
  },
  {
    business: "holistic therapist",
    terms: ['holistic'],
    pitch: "For a holistic therapist, clients want to understand the therapies you offer, get a feel for who you are, and know how to book in. That's exactly what we build: a warm site with your therapies explained, your story, and an easy booking form, so the right clients find you and feel at ease from the start.",
    close: "Thank you, and wishing you a peaceful week.",
  },
  {
    business: "Reiki practitioner",
    terms: ['reiki'],
    pitch: "For a Reiki practitioner, most people want to know what a session feels like, a little about who you are, and whether you offer distance sessions too. That's exactly what we build: a peaceful site with a gentle explanation of Reiki, your session prices, and a way to book, so newcomers feel comfortable reaching out.",
    close: "Warm wishes, and thank you for your time.",
  },
  {
    business: "osteopath",
    terms: ['osteopath'],
    pitch: "For an osteopath, patients want to know you can help with their back, neck or joint pain, that you're registered, and when you can see them. That's exactly what we build: a professional site with the problems you treat, your registration and fees, and online booking, so people in pain can get an appointment quickly.",
    close: "Many thanks, and all the best with the practice.",
  },
  {
    business: "chiropractor",
    terms: ['chiropractor'],
    pitch: "For a chiropractor, patients want to know what happens at a first visit, what it costs, and that you're properly registered. That's exactly what we build: a reassuring site with a guide to the first appointment, your fees and registration, and an easy booking link, so new patients feel comfortable coming in.",
    close: "Kind regards, and hope to speak soon.",
  },
  {
    business: "physio",
    terms: ['physio', 'physiotherapist'],
    pitch: "For a physio, patients want to know you treat their kind of injury, whether you work with their insurer, and how soon they can be seen. That's exactly what we build: a practical site with the injuries and conditions you treat, your fees and insurers, and online booking, so patients can get the help they need without waiting around.",
    close: "Many thanks, and hope the clinic is thriving.",
  },
  {
    business: "sports therapist",
    terms: ['sports therapist', 'sports massage'],
    pitch: "For a sports therapist, active people want to know you understand their sport, what a sports massage costs, and how quickly they can get in. That's exactly what we build: a lively site with the sports and injuries you work with, your treatment prices, and a quick booking button, so clients can get back to training sooner.",
    close: "Cheers, and hope the season treats you well.",
  },
  {
    business: "dog groomer",
    terms: ['dog groomer', 'dog grooming', 'pet groomer', 'pet grooming'],
    pitch: "For a dog groomer, owners want to see before and after photos, check your prices by breed or size, and book a slot that fits around their week. That's exactly what we build: a cheerful site with a gallery of happy pups, your price list, and online booking, so local dog owners can find you and book in easily.",
    close: "Thanks, and give the pups a fuss from us.",
  },
  {
    business: "dog walker",
    terms: ['dog walker'],
    pitch: "For a dog walker, owners want to know their dog is in safe hands, which areas you cover, and whether you do group or solo walks. That's exactly what we build: a friendly site with your experience and insurance, the areas you cover, and your walk prices, so busy owners can book you with complete peace of mind.",
    close: "Cheers, and enjoy the walks this week.",
  },
  {
    business: "dog daycare",
    terms: ['dog daycare'],
    pitch: "For a dog daycare, owners want to see where their dog will spend the day, know you keep everyone safe, and check for space. That's exactly what we build: a welcoming site with photos of the dogs at play, your daily rates, and a way to book a trial day, so owners feel happy leaving their dog with you.",
    close: "Thanks, and have a lovely day with the pack.",
  },
  {
    business: "pet sitter",
    terms: ['pet sitter'],
    pitch: "For a pet sitter, owners want to know you're trustworthy, which animals you look after, and whether you're free while they're away. That's exactly what we build: a homely site with a bit about you and your experience, your services and prices, and a quick enquiry form, so owners can go away knowing their pets are well looked after.",
    close: "Thanks so much, and enjoy your furry guests.",
  },
  {
    business: "pet care business",
    terms: ['pet services'],
    pitch: "For a pet care business, owners want to see everything you offer in one place, what it costs, and that other local owners trust you. That's exactly what we build: a helpful site with your full range of services, your prices, and reviews from happy owners, so local pet owners can find you and get in touch.",
    close: "Thanks a million, and have a lovely week.",
  },

  /* Events, teaching, design, making, transport and print */
  {
    business: "photographer",
    terms: ['photographer', 'photographers', 'photography'],
    pitch: "For a photographer, people want to scroll through your best shots, get a feel for your style and know roughly what a shoot costs. That's exactly what we build: a clean site with a gallery of your work, your packages and prices, and an easy enquiry form, so the right clients can find you and book.",
    close: "Thanks so much, and happy shooting.",
  },
  {
    business: "wedding photographer",
    terms: ['wedding photographer'],
    pitch: "For a wedding photographer, couples want to look through whole weddings you've shot, hear from other couples and check you're free on their date. That's exactly what we build: a stylish site with full wedding galleries, reviews from past couples, and a date enquiry form, so newly engaged couples can fall for your style and book early.",
    close: "All the best for the wedding season ahead.",
  },
  {
    business: "translator",
    terms: ['translator', 'translation'],
    pitch: "For a translator, clients want to know which languages you work in, whether you can certify documents and how quickly they'll get them back. That's exactly what we build: a professional site with your language pairs, the documents you translate and certify, and a quote form for uploading files, so clients can send work your way with confidence.",
    close: "Many thanks, and good luck with everything.",
  },
  {
    business: "interpreter",
    terms: ['interpreting'],
    pitch: "For an interpreter, clients want to know your languages, the settings you work in, like courts, hospitals or business meetings, and whether you're free when they need you. That's exactly what we build: a trustworthy site with your languages and qualifications, the settings you cover, and a booking request form, so organisations can check your credentials and book you quickly.",
    close: "Thanks for your time, and all the best.",
  },
  {
    business: "wedding planner",
    terms: ['wedding planner'],
    pitch: "For a wedding planner, couples want to see weddings you've pulled together, understand how you work and feel they can trust you with their big day. That's exactly what we build: a graceful site with photos of real weddings, your planning packages, and kind words from past couples, so couples can reach out knowing they're in good hands.",
    close: "Warmest wishes, and here's to a busy season.",
  },
  {
    business: "event planner",
    terms: ['event planner'],
    pitch: "For an event planner, clients want to see events you've run, the occasions you handle and a sense that nothing will be left to chance. That's exactly what we build: a sharp site with photos of past events, the services you offer, and a clear enquiry form, so businesses and private clients can brief you straight away.",
    close: "Best wishes, and good luck with your next event.",
  },
  {
    business: "party planner",
    terms: ['party planner'],
    pitch: "For a party planner, people want to see parties you've styled, get ideas for their own celebration and know what you can take off their hands. That's exactly what we build: a cheerful site with photos of past parties, your themes and packages, and an easy enquiry form, so parents and hosts can hand the planning over to you.",
    close: "Have a lovely week, and happy planning.",
  },
  {
    business: "wedding stylist",
    terms: ['wedding stylist'],
    pitch: "For a wedding stylist, couples want to see the looks you've created, from table settings to backdrops, and picture how their venue could feel. That's exactly what we build: a refined site with photos of venues you've dressed, your styling pieces, and a date enquiry form, so couples can see your eye for detail and book you.",
    close: "Warm wishes, and happy styling.",
  },
  {
    business: "DJ",
    terms: ['dj'],
    pitch: "For a DJ, people want to hear a bit of your mixing, see you at real events and know what's included before they book. That's exactly what we build: a bold site with videos from past gigs, your packages and equipment, and a quick booking form, so party hosts and venues can lock in their date fast.",
    close: "Cheers, and here's to plenty more great gigs.",
  },
  {
    business: "wedding DJ",
    terms: ['wedding dj'],
    pitch: "For a wedding DJ, couples want to know you'll read the room, nail their first dance and keep every generation on the dance floor. That's exactly what we build: a lively site with clips from real weddings, reviews from happy couples, and an availability form, so couples can book you for their evening with total peace of mind.",
    close: "Take care, and enjoy all those first dances.",
  },
  {
    business: "entertainer",
    terms: ['entertainer'],
    pitch: "For an entertainer, parents and party hosts want to see you in action, know what the show involves and feel sure the kids will love it. That's exactly what we build: a colourful site with videos of your shows, your party packages, and a booking enquiry form, so families can book you for their next celebration.",
    close: "Thanks a million, and keep those kids smiling.",
  },
  {
    business: "magician",
    terms: ['magician'],
    pitch: "For a magician, people want to see a few tricks in action, know whether you suit weddings, corporate dos or children's parties, and check you're free. That's exactly what we build: a memorable site with performance videos, the events you cover, and a quick booking form, so hosts can see your act for themselves and get you booked in.",
    close: "Thanks a lot, and have a magical week.",
  },
  {
    business: "wedding band",
    terms: ['wedding band'],
    pitch: "For a wedding band, couples want to hear you play, see your set list and know you'll fill the dance floor all night. That's exactly what we build: a vibrant site with live videos, your songs and packages, and an availability form, so couples can book their evening entertainment knowing exactly what they're getting.",
    close: "All the best, and enjoy the gigs ahead.",
  },
  {
    business: "function band",
    terms: ['function band'],
    pitch: "For a function band, bookers want to hear recordings, check you can cover their kind of event, from parties to corporate evenings, and get a clear quote. That's exactly what we build: a confident site with live recordings, your repertoire and packages, and a quick quote form, so event organisers can book you without any chasing.",
    close: "Kind regards, and here's to plenty more bookings.",
  },
  {
    business: "bouncy castle hire business",
    terms: ['bouncy castle'],
    pitch: "For a bouncy castle hire business, parents want to see the castles you have, check the sizes fit their garden and know you deliver to their area. That's exactly what we build: a bright site with photos of every castle, your prices and delivery areas, and an easy booking form, so families can sort their party in minutes.",
    close: "Thanks, and here's to plenty of sunny party days.",
  },
  {
    business: "marquee hire company",
    terms: ['marquee hire'],
    pitch: "For a marquee hire company, customers want to see marquees you've put up, know what size they need and get a rough idea of cost. That's exactly what we build: a smart site with photos of past setups, your marquee sizes and extras, and a quote request form, so event hosts can plan ahead and book early.",
    close: "Many thanks, and wishing you fair weather.",
  },
  {
    business: "party hire business",
    terms: ['party hire'],
    pitch: "For a party hire business, people want to browse what's available, from tables and chairs to lighting and props, and check it's free on their date. That's exactly what we build: a fresh site with your full hire range, clear prices, and a date availability form, so hosts can put together everything they need in one go.",
    close: "Cheers, and all the best with the bookings.",
  },
  {
    business: "event hire company",
    terms: ['event hire'],
    pitch: "For an event hire company, organisers want to see your stock, from staging and furniture to lighting, and know you can deliver and set up on time. That's exactly what we build: a dependable site with photos of your equipment in use, your hire catalogue, and a quote request form, so venues and planners can order with confidence.",
    close: "Thanks for reading, and have a great week.",
  },
  {
    business: "wedding hire business",
    terms: ['wedding hire'],
    pitch: "For a wedding hire business, couples want to browse your decor, see it styled at real venues and check what's free on their date. That's exactly what we build: a pretty site with photos from real weddings, your full hire collection, and a date enquiry form, so couples can picture it all and reserve their pieces early.",
    close: "Warmest wishes, and enjoy all the celebrations.",
  },
  {
    business: "tutor",
    terms: ['tutor', 'tuition', 'private tutor'],
    pitch: "For a tutor, parents want to know which subjects and levels you teach, how lessons work and that their child is in safe hands. That's exactly what we build: a friendly site with your subjects, experience and DBS check, feedback from parents, and a trial lesson booking form, so families can get their child started with you straight away.",
    close: "Thanks so much, and good luck this term.",
  },
  {
    business: "music teacher",
    terms: ['music teacher'],
    pitch: "For a music teacher, students and parents want to know which instruments and grades you teach, what lessons cost and when you have space. That's exactly what we build: a warm site with your instruments and teaching style, lesson prices, and a form to request a lesson slot, so new pupils can find the right teacher and start playing.",
    close: "Many thanks, and happy teaching.",
  },
  {
    business: "football coach",
    terms: ['football coach'],
    pitch: "For a football coach, parents and players want to know the age groups you coach, where and when sessions run and how to sign up. That's exactly what we build: a sporty site with your sessions and age groups, pitch locations and times, and an easy registration form, so new players can join and get training in no time.",
    close: "All the best to you and the team this season.",
  },
  {
    business: "swim school",
    terms: ['swim school'],
    pitch: "For a swim school, parents want to know the class levels, which pools you use, lesson times and whether there's a space for their child. That's exactly what we build: a clear site with your class levels and timetables, pool locations, and a waiting list form, so parents can find the right class and get their little ones swimming.",
    close: "Take care, and happy swimming.",
  },
  {
    business: "sports coach",
    terms: ['sports coach'],
    pitch: "For a sports coach, people want to see the sports and ages you cover, what a session looks like and how much it costs. That's exactly what we build: a dynamic site with your coaching programmes, session prices, and a quick booking form, so clubs, schools and families can get training booked in with you.",
    close: "All the best, and enjoy the coaching.",
  },
  {
    business: "martial arts club",
    terms: ['martial arts'],
    pitch: "For a martial arts club, new starters want to know the styles you teach, the class times for kids and adults and that beginners are welcome. That's exactly what we build: a strong site with your class timetable, your instructors and gradings, and a free trial class form, so beginners can walk through the door with confidence.",
    close: "Best wishes to you and everyone at the club.",
  },
  {
    business: "karate club",
    terms: ['karate'],
    pitch: "For a karate club, parents and adults want to know which classes suit them, who does the teaching and how the belt gradings work. That's exactly what we build: a focused site with your class times and age groups, your instructors and belt system, and a trial lesson form, so new students can turn up for their first class.",
    close: "Cheers, and keep up the good work at the dojo.",
  },
  {
    business: "architect",
    terms: ['architect', 'architects'],
    pitch: "For an architect, clients want to see finished projects, understand your approach and feel confident you can guide them through planning. That's exactly what we build: a sleek site with a portfolio of your projects, the services you offer from concept to completion, and a consultation request form, so homeowners and developers can start a conversation about their plans.",
    close: "Kind regards, and all the best with your projects.",
  },
  {
    business: "architectural designer",
    terms: ['architectural designer'],
    pitch: "For an architectural designer, homeowners want to see extensions and conversions you've drawn up, know you can handle planning and building regs, and get a feel for fees. That's exactly what we build: a crisp site with before and after project photos, your design and planning services, and a quote request form, so homeowners can get their plans moving.",
    close: "Good luck with the drawings, and speak soon.",
  },
  {
    business: "interior designer",
    terms: ['interior designer'],
    pitch: "For an interior designer, clients want to see rooms you've transformed, get a sense of your style and understand what working with you looks like. That's exactly what we build: a tasteful site with a portfolio of your rooms, your design process, and a consultation booking form, so clients who love your style can reach you right away.",
    close: "Warm wishes, and enjoy your next project.",
  },
  {
    business: "kitchen designer",
    terms: ['kitchen designer'],
    pitch: "For a kitchen designer, homeowners want to see kitchens you've designed and fitted, the ranges and finishes you offer and how to book a design visit. That's exactly what we build: a handsome site with galleries of finished kitchens, your styles and finishes, and a design appointment form, so homeowners can start planning their new kitchen with you.",
    close: "Best wishes, and happy designing.",
  },
  {
    business: "garden designer",
    terms: ['garden designer'],
    pitch: "For a garden designer, homeowners want to see gardens you've transformed, understand your design process and picture what their own space could become. That's exactly what we build: a calm site with before and after garden photos, your process from first visit to planting, and a consultation form, so homeowners can see what's possible and book you in.",
    close: "Happy gardening, and thanks for your time.",
  },
  {
    business: "machinery repair business",
    terms: ['machinery repair'],
    pitch: "For a machinery repair business, customers want to know what you work on, whether you come out to them and how fast you can get them running again. That's exactly what we build: a practical site with the equipment you repair, the areas you cover, and a tap to call button, so anyone with broken kit can reach you fast.",
    close: "Thanks, and keep those machines running.",
  },
  {
    business: "plant repair business",
    terms: ['plant repair'],
    pitch: "For a plant repair business, contractors want to know you service their diggers, dumpers and rollers, and that you'll get to site fast when something breaks. That's exactly what we build: a sturdy site with the plant you repair, the areas you cover, and a call button, so contractors can cut their downtime and get back to work.",
    close: "Speak soon, and all the best on site.",
  },
  {
    business: "welder",
    terms: ['welding', 'welder'],
    pitch: "For a welder, customers want to see your welds and repairs, know whether you come to them or work from a workshop and get a quick quote. That's exactly what we build: a rugged site with photos of your jobs, your mobile and workshop services, and a quote request form, so customers can get their job sorted.",
    close: "Cheers, and stay safe behind the mask.",
  },
  {
    business: "fabricator",
    terms: ['fabrication', 'fabricator'],
    pitch: "For a fabricator, customers want to see things you've made, from steel frames to brackets, and know you can work to their drawings. That's exactly what we build: a solid site with a gallery of your fabrication work, the materials you handle, and a quote form for their drawings, so customers can send their plans straight over.",
    close: "Many thanks, and all the best in the workshop.",
  },
  {
    business: "metalwork business",
    terms: ['metalwork'],
    pitch: "For a metalwork business, customers want to see your craftsmanship, from gates and railings to decorative pieces, and know you can make something to fit. That's exactly what we build: a classic site with photos of finished pieces, the metals and finishes you work with, and a commission enquiry form, so customers can bring their ideas to you.",
    close: "Thanks so much, and keep the sparks flying.",
  },
  {
    business: "bespoke joiner",
    terms: ['bespoke joinery'],
    pitch: "For a bespoke joiner, homeowners want to see your finished work, from doors and windows to fitted shelving, and know you can make what they have in mind. That's exactly what we build: a timeless site with photos of your joinery, the timbers you use, and an enquiry form, so homeowners can talk their ideas through with you.",
    close: "Cheers, and all the best at the bench.",
  },
  {
    business: "custom furniture maker",
    terms: ['custom furniture'],
    pitch: "For a custom furniture maker, customers want to see pieces you've made, understand how the design process works and get a feel for what a commission costs. That's exactly what we build: a characterful site with a gallery of your furniture, your commission process, and an enquiry form, so customers can start designing something unique with you.",
    close: "Best wishes, and enjoy the next commission.",
  },
  {
    business: "bespoke wardrobe company",
    terms: ['wardrobes', 'bespoke wardrobes'],
    pitch: "For a bespoke wardrobe company, homeowners want to see wardrobes you've fitted into awkward spaces, choose from your finishes and book someone to measure up. That's exactly what we build: a tidy site with photos of finished wardrobes, your doors and interiors, and a free measure booking form, so homeowners can get their bedroom sorted without the hassle.",
    close: "Thanks so much, and have a lovely day.",
  },
  {
    business: "staircase maker",
    terms: ['staircase'],
    pitch: "For a staircase maker, homeowners want to see staircases you've built, the styles and timbers on offer and whether you can work with their space. That's exactly what we build: a polished site with photos of finished staircases, your styles and balustrade options, and a survey request form, so homeowners can start planning the centrepiece of their home.",
    close: "Cheers, and all the best with the next staircase.",
  },
  {
    business: "furniture maker",
    terms: ['furniture maker', 'bespoke furniture'],
    pitch: "For a furniture maker, customers want to see pieces from your workshop, learn about the woods you use and know how to order something made for them. That's exactly what we build: a natural site with a gallery of your furniture, your story, and a commission enquiry form, so people who value real craftsmanship can find you.",
    close: "Best wishes, and happy making.",
  },
  {
    business: "cabinet maker",
    terms: ['cabinet maker'],
    pitch: "For a cabinet maker, clients want to see the detail in your work, from fitted cabinetry to freestanding pieces, and know you can build around their space. That's exactly what we build: a precise site with photos of your craftsmanship, the rooms you fit out, and a commission enquiry form, so clients can bring their plans to you.",
    close: "Kind regards, and enjoy your time in the workshop.",
  },
  {
    business: "haulage company",
    terms: ['haulage'],
    pitch: "For a haulage company, customers want to know what you can move, where you run to and whether you've got capacity when they need it. That's exactly what we build: a businesslike site with your fleet and load types, the routes you cover, and a quote request form, so businesses can book loads with you quickly.",
    close: "Thanks so much, and wishing you a busy few months.",
  },
  {
    business: "courier",
    terms: ['courier'],
    pitch: "For a courier, customers want to know what you'll carry, where you deliver and how quickly they can get a price. That's exactly what we build: a nimble site with your delivery services, the areas you cover, and an instant quote form, so local businesses can book a collection in a few taps.",
    close: "Thanks so much, and safe driving.",
  },
  {
    business: "same day courier",
    terms: ['sameday courier'],
    pitch: "For a same day courier, customers usually need something moved urgently, so they want to see you're available now and get a price straight away. That's exactly what we build: a fast site with a tap to call button, your vehicle sizes, and a quick quote form, so urgent jobs come straight to you instead of the big networks.",
    close: "Best wishes, and keep those wheels turning.",
  },
  {
    business: "pallet delivery business",
    terms: ['palletised'],
    pitch: "For a pallet delivery business, customers want to know the pallet sizes and weights you take, where you deliver and how quickly it will arrive. That's exactly what we build: a straightforward site with your pallet services and prices, your delivery coverage, and an online quote form, so businesses can get their pallets booked in without phoning around.",
    close: "Have a smooth week, and thanks for reading.",
  },
  {
    business: "taxi firm",
    terms: ['taxi'],
    pitch: "For a taxi firm, people want a number they can ring right now and a sense that you'll turn up on time. That's exactly what we build: a punchy site with a tap to call button, your fares and areas, and a booking form for later trips, so people can get a cab with you in no time.",
    close: "Cheers, and have a steady shift.",
  },
  {
    business: "private hire firm",
    terms: ['private hire'],
    pitch: "For a private hire firm, customers want to book ahead, know the fare upfront and trust that a licensed driver will be there when promised. That's exactly what we build: a reliable site with an online booking form, your vehicles and fares, and your licensing details, so customers can book their journeys in a few clicks.",
    close: "Take care, and all the best with the fleet.",
  },
  {
    business: "chauffeur service",
    terms: ['chauffeur'],
    pitch: "For a chauffeur service, clients want to see your cars, feel reassured by your professionalism and book with complete discretion. That's exactly what we build: a classy site with photos of your fleet, the occasions you cover from weddings to corporate travel, and a private booking form, so discerning clients can reserve their car with ease.",
    close: "Kind regards, and wishing you smooth journeys.",
  },
  {
    business: "airport transfer service",
    terms: ['airport transfer'],
    pitch: "For an airport transfer service, travellers want a fixed fare, a driver who tracks their flight and the certainty you'll be there however early it is. That's exactly what we build: a reassuring site with airport fares at a glance, a booking form for flights and pickups, and your meet and greet details, so travellers can book and relax.",
    close: "Thanks so much, and safe travels.",
  },
  {
    business: "minicab firm",
    terms: ['minicab'],
    pitch: "For a minicab firm, locals want a quick way to book, a fair price they can trust and a car that shows up on time. That's exactly what we build: a handy site with a tap to call button, your standard fares, and an online booking form, so regular customers stick with you instead of the apps.",
    close: "Cheers, and have a good one.",
  },
  {
    business: "freight forwarder",
    terms: ['freight forwarder'],
    pitch: "For a freight forwarder, importers and exporters want to know which routes you handle, that you can deal with customs and how to get a quote. That's exactly what we build: a credible site with your sea, air and road services, customs clearance support, and a quote request form, so businesses can hand their shipments over with confidence.",
    close: "Many thanks, and smooth sailing ahead.",
  },
  {
    business: "logistics company",
    terms: ['logistics'],
    pitch: "For a logistics company, businesses want to know what you can take off their plate and that their stock is in safe hands. That's exactly what we build: a modern site with your warehousing and distribution services, the sectors you work with, and a consultation request form, so growing businesses can see you're the partner they need.",
    close: "Kind regards, and wishing the business well.",
  },
  {
    business: "print shop",
    terms: ['printer', 'printers'],
    pitch: "For a print shop, customers want to see what you can print, from business cards to banners, get a rough price and know when it'll be ready. That's exactly what we build: a vivid site with your print products and prices, examples of recent work, and an artwork upload form, so local businesses can send their order straight over.",
    close: "Thanks for your time, and keep the presses rolling.",
  },
  {
    business: "sign maker",
    terms: ['sign maker'],
    pitch: "For a sign maker, businesses want to see signs you've made and fitted, from shopfronts to site boards, and get a quote for their own. That's exactly what we build: a striking site with photos of installed signs, the signage you make, and a quote form with photo upload, so businesses can get their new sign up fast.",
    close: "All the best, and keep the signs going up.",
  },
  {
    business: "signwriter",
    terms: ['signwriter'],
    pitch: "For a signwriter, customers want to see your lettering up close, on shopfronts, vans and boards, and know that every piece is painted by hand. That's exactly what we build: a charming site with photos of your lettering, the surfaces you paint on, and a commission enquiry form, so businesses wanting a traditional look can find you.",
    close: "Many thanks, and steady hands to you.",
  },
  {
    business: "vehicle wrapping business",
    terms: ['vehicle wrapping'],
    pitch: "For a vehicle wrapping business, customers want to see vans and cars you've wrapped, the colours and finishes on offer and a price for their own. That's exactly what we build: a glossy site with before and after photos, your wrap and livery options, and a quote request form, so van owners and car enthusiasts can book in.",
    close: "Speak soon, and all the best with the wraps.",
  },
  {
    business: "graphics company",
    terms: ['graphics'],
    pitch: "For a graphics company, customers want to see logos, displays and printed graphics you've produced, and know you can take a job from idea to finish. That's exactly what we build: a creative site with a portfolio of your work, the services you offer, and a project brief form, so businesses can get their branding and displays sorted.",
    close: "Thanks for reading, and enjoy the creative work.",
  },
  {
    business: "bespoke manufacturer",
    terms: ['bespoke manufacture'],
    pitch: "For a bespoke manufacturer, clients want to see what you've produced, the processes you use and whether you can handle small or large runs. That's exactly what we build: a capable site with examples of past jobs, the materials you work in, and a quote form for drawings, so businesses can send their ideas over and get them made.",
    close: "Best regards, and good luck with production.",
  },
  {
    business: "made to order business",
    terms: ['custom made'],
    pitch: "For a made to order business, customers want to see things you've made before, know what they can personalise and understand how ordering works. That's exactly what we build: a personal site with a gallery of past orders, your options and prices, and a custom order form, so customers can describe exactly what they want.",
    close: "Thanks, and here's to plenty more orders.",
  },
  {
    business: "craft maker",
    terms: ['craft maker'],
    pitch: "For a craft maker, people want to see your handmade pieces, hear the story behind them and know how to buy or commission one. That's exactly what we build: a lovely site with a gallery of your makes, the story of your craft, and an order enquiry form, so fans of handmade can buy straight from you.",
    close: "Warm wishes, and happy crafting.",
  },
];

/** A business matched to a broad sector (lib/sectors.js) but no pitch of its own. */
export const SECTOR_PITCHES = {
  "salon": {
    "business": "salon",
    "pitch": "New clients want to see your work, your treatments and your prices, and book without having to ring. That's exactly what we build: a beautiful site with your treatments, lovely photos of your work, and a button so they can book or call you straight from their phone.",
    "close": "Thanks so much, and have a lovely day."
  },
  "trades": {
    "business": "trade",
    "pitch": "For a trade, most people just want to see a few jobs you've done and be able to tap to call. That's exactly what we build: a clean one page site with photos of your work, the areas you cover, and a call button, so new customers can find you and get straight through.",
    "close": "Cheers, and all the best with the work."
  },
  "food": {
    "business": "food business",
    "pitch": "For a place like yours, people want to check the menu, your opening hours and how to order before they come in. That's exactly what we build: a site with your menu, great photos of your food, and a button to call or order straight from their phone.",
    "close": "Thanks so much, and hope you're keeping busy."
  },
  "motor": {
    "business": "garage",
    "pitch": "For a garage, people want to see what you do, check your hours and book their car in. That's exactly what we build: a clear site with your services, your opening hours and a call button, so new customers can find you and get booked in easily.",
    "close": "Cheers, and all the best."
  },
  "fitness": {
    "business": "health or fitness business",
    "pitch": "For somewhere like yours, people want to see what you offer and your prices or timetable before they commit. That's exactly what we build: a welcoming site with your classes or treatments, your prices, and a button to book or call straight from their phone.",
    "close": "Thanks so much, and have a great day."
  },
  "shop": {
    "business": "shop",
    "pitch": "For a shop, people want to see what you stock, where you are and when you're open. That's exactly what we build: a site with photos of what you sell, your opening hours and where to find you, so new customers come straight to your door.",
    "close": "Thanks so much, and have a lovely day."
  },
  "pets": {
    "business": "pet business",
    "pitch": "Pet owners want to see the pets you've looked after, your prices and how to book before they trust you with theirs. That's exactly what we build: a friendly site with photos of your happy customers, your services and prices, and a button to book or call straight from their phone.",
    "close": "Thanks so much, and have a great day."
  }
};

/** Any business at all. */
export const GENERAL_PITCH = {
  "business": "local business",
  "pitch": "Most people look a business up online before they get in touch, and that's where a good website wins you the job. That's exactly what we build: a clean, professional site showing what you do, photos of your work, and a button so new customers can call or message you straight from their phone.",
  "close": "Thanks so much, and have a great day."
};
